- name: Criar grupo acesso_ssh
  ansible.builtin.group:
    name: acesso_ssh
    state: present

- name: Criar grupo "ifpb"
  ansible.builtin.group:
    name: ifpb
    state: present
    
- name: Criar Usu√°rios
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "ifpb,acesso_ssh"
    state: present
  loop:
   - samuel
   - isabel
